name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - run: |
        npm ci
        npm run bootstrap
    - run: npm test
    - run: npm run lint
